- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.27.1
  hooks:
  - id: markdownlint
- repo: https://github.com/trussworks/pre-commit-hooks
  rev: v1.1.0
  hooks:
  - id: markdown-toc
